ALTER TABLE ATH_ASSC_USR DROP PRIMARY KEY CASCADE;

DROP TABLE ATH_ASSC_USR CASCADE CONSTRAINTS;

ALTER TABLE ATH_CTRLR DROP PRIMARY KEY CASCADE;

DROP TABLE ATH_CTRLR CASCADE CONSTRAINTS;

ALTER TABLE ATH_CNFG DROP PRIMARY KEY CASCADE;

DROP TABLE ATH_CNFG CASCADE CONSTRAINTS;

ALTER TABLE ATH_ROL DROP PRIMARY KEY CASCADE;

DROP TABLE ATH_ROL CASCADE CONSTRAINTS;

ALTER TABLE ATH_GRP DROP PRIMARY KEY CASCADE;

DROP TABLE ATH_GRP CASCADE CONSTRAINTS;

ALTER TABLE ATH_GRP_ROL DROP PRIMARY KEY CASCADE;

DROP TABLE ATH_GRP_ROL CASCADE CONSTRAINTS;

ALTER TABLE ATH_USR_GRP DROP PRIMARY KEY CASCADE;

DROP TABLE ATH_USR_GRP CASCADE CONSTRAINTS;

ALTER TABLE ATH_OPRN DROP PRIMARY KEY CASCADE;

DROP TABLE ATH_OPRN CASCADE CONSTRAINTS;

ALTER TABLE ATH_ACSS_CTRL_LST DROP PRIMARY KEY CASCADE;

DROP TABLE ATH_ACSS_CTRL_LST CASCADE CONSTRAINTS;

ALTER TABLE ATH_LOG DROP PRIMARY KEY CASCADE;

DROP TABLE ATH_LOG CASCADE CONSTRAINTS;

ALTER TABLE ATH_APP DROP PRIMARY KEY CASCADE;

DROP TABLE ATH_APP CASCADE CONSTRAINTS;

DROP SEQUENCE ATH_CTRLR_SEQ;

DROP SEQUENCE ATH_GRP_SEQ;

DROP SEQUENCE ATH_ROL_SEQ;

DROP SEQUENCE ATH_USR_SEQ;

DROP SEQUENCE ATH_LOG_SEQ;

DROP SEQUENCE ATH_APP_SEQ;